### ISSUE TITLE
I don't like this comment

### ISSUE THREAD

**Issue by yazenkk2** [yazenkk/testing_issues#1]
https://github.com/yazenkk/testing_issues/blob/aac36a6409b704c70da6152133a5de2eb8bc2ddd/file1#L3

pls remove this comment or restate it more gently

**Comment by yazenkk** [comment]
Hi @yazenkk2, Sorry about that. I'll fix it now.

**Comment by yazenkk** [comment]
how about we try X instead

**Comment by yazenkk** [comment]
Closing this issue now after kk2 un-"watched" the repo
